In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
data = df.drop(labels="ID",axis=1).to_numpy()
target = df["ID"].to_numpy()

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3,random_state=109) 


In [4]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.55890324 -0.86901997 -0.29353217]
 [-0.23836574  2.11503853 -0.81813818]
 [-0.47876886 -0.86901997  0.2893634 ]
 ...
 [ 1.60472484  0.1256662  -0.70155906]
 [-0.15823137  1.91610129 -0.93471729]
 [-1.03970947 -0.73639515  0.81396942]]
[[ 1.84512796 -0.13958345 -0.75984862]
 [-0.078097    2.11503853 -0.93471729]
 [ 0.96364986  0.98772754 -0.64326951]
 ...
 [-0.87944073 -0.67008274  0.81396942]
 [-1.03970947 -0.40483309  0.52252163]
 [-1.11984385 -0.80270756  1.97976056]]


In [5]:
#Import Gradient Boosting model
from sklearn.ensemble import GradientBoostingClassifier
# Create a Gradient Boosting Classifier
clf = GradientBoostingClassifier()

# Train the model using the training sets
clf.fit(X_train, y_train)

# Predict the response for the test dataset
y_pred = clf.predict(X_test)


In [6]:
import pickle

# Save the model to a .pkl file
with open('model.pkl', 'wb') as file:
    pickle.dump(clf, file)